const $ = (s) => document.querySelector(s);
const seed = [{id:1,nome:'Marina Costa',loja:'Casa Norte',whatsapp:'11987654321',mensagem:'Reposicionar a marca',status:'novo',notas:'',created_at:'2026-10-04T16:20:00',origem:'instagram'},{id:2,nome:'Rafael Mendes',loja:'Onda Studio',whatsapp:'21991234567',mensagem:'Lançamento do produto',status:'contatado',notas:'Retornar na terça',created_at:'2026-10-03T12:10:00',origem:'indicação'}];
let leads = JSON.parse(localStorage.getItem('vello-leads') || 'null') || seed; let activeStatus = '';
const labels = {novo:'Novo',contatado:'Contatado',prototipo:'Protótipo',orcamento:'Orçamento',fechado:'Fechado',perdido:'Perdido'};
const esc = (v) => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const save = () => localStorage.setItem('vello-leads', JSON.stringify(leads));
const formatDate = (v) => new Date(v).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit',year:'2-digit'});
const formatPhone = (v) => { const d=String(v).replace(/\D/g,'').slice(-11); return d.length===11?`(${d.slice(0,2)}) ${d.slice(2,7)}-${d.slice(7)}`:v; };
function showPanel(){ $('#landing-view').classList.add('hidden'); $('#panel-view').classList.remove('hidden'); renderPanel(); window.scrollTo(0,0); }
function showLanding(){ $('#panel-view').classList.add('hidden'); $('#landing-view').classList.remove('hidden'); }
document.querySelectorAll('[data-open-panel]').forEach(b=>b.addEventListener('click',showPanel)); document.querySelectorAll('[data-back]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();showLanding()}));
$('[data-scroll-form]').addEventListener('click',()=>$('#contato').scrollIntoView({behavior:'smooth'}));
$('#lead-form').addEventListener('submit',e=>{e.preventDefault(); const data=Object.fromEntries(new FormData(e.target)); leads.unshift({id:Date.now(),...data,status:'novo',notas:'',created_at:new Date().toISOString(),origem:'landing'}); save(); e.target.reset(); $('#form-feedback').innerHTML='<p class="success">Recebido. Em breve a gente entra em contato. ✳</p>'; setTimeout(()=>$('#form-feedback').innerHTML='',5000); });
function filtered(){const q=($('#search')?.value||'').toLowerCase().trim(); return leads.filter(l=>(!activeStatus||l.status===activeStatus)&&(!q||[l.nome,l.loja,l.whatsapp,l.mensagem,l.origem].join(' ').toLowerCase().includes(q)));}
function renderPanel(){const counts=Object.fromEntries(Object.keys(labels).map(k=>[k,leads.filter(l=>l.status===k).length])); $('#stats').innerHTML=`<button class="stat ${!activeStatus?'active':''}" data-stat=""><b>${leads.length}</b><span>Todos os leads</span></button>`+Object.entries(labels).map(([k,v])=>`<button class="stat ${activeStatus===k?'active':''}" data-stat="${k}"><b>${counts[k]}</b><span>${v}</span></button>`).join(''); const rows=filtered(); $('#lead-count').textContent=`${rows.length} ${rows.length===1?'lead':'leads'}`; $('#lead-list').innerHTML=rows.length?`<table class="lead-table"><thead><tr><th>Data</th><th>Lead</th><th>WhatsApp</th><th>Origem</th><th>Status</th><th>Notas</th><th></th></tr></thead><tbody>${rows.map(l=>`<tr data-id="${l.id}"><td data-label="Data" class="sub">${formatDate(l.created_at)}</td><td data-label="Lead"><div class="lead-main">${esc(l.loja)}</div><div class="sub">${esc(l.nome)} · ${esc(l.mensagem)}</div></td><td data-label="WhatsApp"><a class="sub" href="https://wa.me/55${String(l.whatsapp).replace(/\D/g,'')}" target="_blank">${formatPhone(l.whatsapp)}</a></td><td data-label="Origem" class="sub">${esc(l.origem)}</td><td data-label="Status"><select class="status-select">${Object.entries(labels).map(([k,v])=>`<option value="${k}" ${l.status===k?'selected':''}>${v}</option>`).join('')}</select></td><td data-label="Notas"><textarea class="notes" rows="1">${esc(l.notas)}</textarea></td><td><button class="delete" title="Excluir lead">×</button></td></tr>`).join('')}</tbody></table>`:'<div class="empty">Nenhum lead encontrado com esse filtro.</div>'; $('#stats').querySelectorAll('[data-stat]').forEach(b=>b.onclick=()=>{activeStatus=b.dataset.stat;$('#status-filter').value=activeStatus;renderPanel()}); document.querySelectorAll('.status-select').forEach(s=>s.onchange=()=>{const l=leads.find(x=>x.id===+s.closest('tr').dataset.id);l.status=s.value;save();renderPanel()}); document.querySelectorAll('.notes').forEach(n=>n.onchange=()=>{const l=leads.find(x=>x.id===+n.closest('tr').dataset.id);l.notas=n.value;save()}); document.querySelectorAll('.delete').forEach(b=>b.onclick=()=>{const id=+b.closest('tr').dataset.id;if(confirm('Excluir este lead?')){leads=leads.filter(l=>l.id!==id);save();renderPanel()}});}
$('#search').addEventListener('input',renderPanel); $('#status-filter').addEventListener('change',e=>{activeStatus=e.target.value;renderPanel()}); $('#export-button').addEventListener('click',()=>{const cols=['created_at','nome','loja','whatsapp','status','notas','origem','mensagem'];const csv='\ufeff'+[cols.join(';'),...filtered().map(l=>cols.map(c=>`"${String(l[c]??'').replace(/"/g,'""')}"`).join(';'))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='leads-vello.csv';a.click()});
