import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const supabase=createClient('https://eudnklhzqohdciygriel.supabase.co','sb_publishable_smQwFQlfKgnS8VhOIoUoig_VLtBSS5J');
const $=s=>document.querySelector(s);let leads=[],activeStatus='';const labels={novo:'Novo',contatado:'Contatado',prototipo:'Protótipo',orcamento:'Orçamento',fechado:'Fechado',perdido:'Perdido'};
const recoveryHash=window.location.hash.includes('type=recovery')||window.location.hash.includes('access_token=');const recoveryCode=new URLSearchParams(window.location.search).get('code');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const formatDate=v=>new Date(v).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit',year:'2-digit'});const formatPhone=v=>{const d=String(v).replace(/\D/g,'').slice(-11);return d.length===11?`(${d.slice(0,2)}) ${d.slice(2,7)}-${d.slice(7)}`:v};
const showAuth=()=>{$('#auth-modal').classList.remove('hidden');$('#auth-email').focus()};const hideAuth=()=>$('#auth-modal').classList.add('hidden');const showPanel=()=>{$('#landing-view').classList.add('hidden');$('#panel-view').classList.remove('hidden');window.scrollTo(0,0)};const showLanding=()=>{$('#panel-view').classList.add('hidden');$('#landing-view').classList.remove('hidden')};
document.querySelectorAll('[data-open-panel]').forEach(b=>b.addEventListener('click',showAuth));document.querySelectorAll('[data-back]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();showLanding()}));$('[data-close-auth]').addEventListener('click',hideAuth);$('[data-scroll-form]').addEventListener('click',()=>$('#contato').scrollIntoView({behavior:'smooth'}));
async function openRecovery(){if(recoveryHash){$('#reset-modal').classList.remove('hidden');window.history.replaceState({},document.title,window.location.pathname);return}if(recoveryCode){const {error}=await supabase.auth.exchangeCodeForSession(recoveryCode);if(!error){$('#reset-modal').classList.remove('hidden');window.history.replaceState({},document.title,window.location.pathname)}else{$('#auth-feedback').textContent='Este link expirou. Solicite uma nova redefinição.';showAuth()}}}openRecovery();
$('#reset-form').addEventListener('submit',async e=>{e.preventDefault();const f=$('#reset-feedback'),p=$('#reset-password').value,c=$('#reset-confirm').value;if(p!==c){f.textContent='As senhas não conferem.';return}if(p.length<8){f.textContent='Use pelo menos 8 caracteres.';return}f.textContent='Salvando...';const {error}=await supabase.auth.updateUser({password:p});if(error){f.textContent='O link expirou. Solicite uma nova redefinição.';return}f.className='success';f.textContent='Senha atualizada. Agora você já pode entrar na área interna.';setTimeout(()=>{$('#reset-modal').classList.add('hidden');showAuth()},900)});
$('#auth-form').addEventListener('submit',async e=>{e.preventDefault();const f=$('#auth-feedback');f.textContent='Entrando...';const {error}=await supabase.auth.signInWithPassword({email:$('#auth-email').value.trim(),password:$('#auth-password').value});if(error){f.textContent='E-mail ou senha inválidos.';return}f.textContent='';hideAuth();showPanel();await loadLeads()});$('#logout-button').addEventListener('click',async()=>{await supabase.auth.signOut();showLanding()});
$('#lead-form').addEventListener('submit',async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target)),p=new URLSearchParams(location.search);const {error}=await supabase.from('vello_leads').insert({nome:d.nome,loja:d.loja,whatsapp:d.whatsapp,instagram:d.mensagem||null,origem:'landing',pagina:location.pathname,utm_source:p.get('utm_source'),utm_medium:p.get('utm_medium'),utm_campaign:p.get('utm_campaign'),utm_content:p.get('utm_content'),utm_term:p.get('utm_term')});if(error){$('#form-feedback').innerHTML='<p class="error">Não foi possível enviar agora. Tente novamente.</p>';return}e.target.reset();$('#form-feedback').innerHTML='<p class="success">Recebido. Em breve a gente entra em contato. ✳</p>';setTimeout(()=>$('#form-feedback').innerHTML='',5000)});
async function loadLeads(){const {data,error}=await supabase.from('vello_leads').select('*').order('created_at',{ascending:false});if(error){$('#lead-list').innerHTML='<div class="empty">Não foi possível carregar os leads.</div>';return}leads=data||[];renderPanel()};function filtered(){const q=($('#search')?.value||'').toLowerCase().trim();return leads.filter(l=>(!activeStatus||l.status===activeStatus)&&(!q||[l.nome,l.loja,l.whatsapp,l.instagram,l.origem].join(' ').toLowerCase().includes(q)))}
function renderPanel(){const counts=Object.fromEntries(Object.keys(labels).map(k=>[k,leads.filter(l=>l.status===k).length]));$('#stats').innerHTML=`<button class="stat ${!activeStatus?'active':''}" data-stat=""><b>${leads.length}</b><span>Todos os leads</span></button>`+Object.entries(labels).map(([k,v])=>`<button class="stat ${activeStatus===k?'active':''}" data-stat="${k}"><b>${counts[k]}</b><span>${v}</span></button>`).join('');const rows=filtered();$('#lead-count').textContent=`${rows.length} ${rows.length===1?'lead':'leads'}`;$('#lead-list').innerHTML=rows.length?`<table class="lead-table"><thead><tr><th>Data</th><th>Lead</th><th>WhatsApp</th><th>Origem</th><th>Status</th><th>Notas</th></tr></thead><tbody>${rows.map(l=>`<tr data-id="${l.id}"><td data-label="Data" class="sub">${formatDate(l.created_at)}</td><td data-label="Lead"><div class="lead-main">${esc(l.loja)}</div><div class="sub">${esc(l.nome)} · ${esc(l.instagram||'')}</div></td><td data-label="WhatsApp"><a class="sub" href="https://wa.me/55${String(l.whatsapp).replace(/\D/g,'')}" target="_blank">${formatPhone(l.whatsapp)}</a></td><td data-label="Origem" class="sub">${esc(l.origem||'landing')}</td><td data-label="Status"><select class="status-select">${Object.entries(labels).map(([k,v])=>`<option value="${k}" ${l.status===k?'selected':''}>${v}</option>`).join('')}</select></td><td data-label="Notas"><textarea class="notes" rows="1">${esc(l.notas)}</textarea></td></tr>`).join('')}</tbody></table>`:'<div class="empty">Nenhum lead encontrado com esse filtro.</div>';document.querySelectorAll('[data-stat]').forEach(b=>b.onclick=()=>{activeStatus=b.dataset.stat;$('#status-filter').value=activeStatus;renderPanel()});document.querySelectorAll('.status-select').forEach(s=>s.onchange=async()=>{await supabase.from('vello_leads').update({status:s.value}).eq('id',Number(s.closest('tr').dataset.id));await loadLeads()});document.querySelectorAll('.notes').forEach(n=>n.onchange=async()=>{await supabase.from('vello_leads').update({notas:n.value}).eq('id',Number(n.closest('tr').dataset.id))})}
$('#search').addEventListener('input',renderPanel);$('#status-filter').addEventListener('change',e=>{activeStatus=e.target.value;renderPanel()});$('#export-button').addEventListener('click',()=>{const cols=['created_at','nome','loja','whatsapp','status','notas','origem','instagram'];const csv='\ufeff'+[cols.join(';'),...filtered().map(l=>cols.map(c=>`"${String(l[c]??'').replace(/"/g,'""')}"`).join(';'))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='leads-vello.csv';a.click()});
$('#forgot-password').addEventListener('click',async()=>{const f=$('#auth-feedback'),email=$('#auth-email').value.trim();if(!email){f.textContent='Digite seu e-mail para receber o link.';$('#auth-email').focus();return}f.textContent='Enviando link...';const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});if(error){f.textContent=error.message.includes('rate limit')?'Aguarde alguns minutos antes de solicitar outro link.':'Não foi possível enviar o link agora.';return}f.className='success';f.textContent='Link enviado. Verifique sua caixa de entrada e o spam.'});
